# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c684d5c455c40a88ba1dfc33d8cea1c61930e05a983f732f858b12fac163534d12a1fb6bc3acaf0cb5bd973154ba41c38de8856fb019eb501ddb985cc720a439

test:
  secret_key_base: 7291588843dcbd761de6a1888d413ecf48d17566f817ce1513913527756ae80faa90c7d7a83398b110f3efd0fbae1c1ff8a309cd831b13b25d4f94ba43ce9112

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
